version: "2"

linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - err113
    - errcheck
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gomoddirectives
    - gomodguard
    - gosec
    - ireturn
    - lll
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - predeclared
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - "-ST1000"
        - "-SA9003"

  exclusions:
    paths:
      - ".*_test\\.go$"
      - "third_party/"

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m